# Generated by Django 4.2 on 2023-06-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operazione', models.CharField(max_length=5)),
                ('num_contratti', models.IntegerField()),
                ('descrizione', models.CharField(max_length=200)),
                ('prezzo', models.FloatField()),
                ('valuta', models.CharField(max_length=3)),
                ('data_ora', models.DateTimeField()),
                ('commissione', models.FloatField()),
                ('profitto_perdita', models.FloatField(blank=True, max_length=100, null=True)),
                ('commento', models.CharField(max_length=200)),
                ('descrizione12', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Trade2',
            fields=[
                ('id2', models.AutoField(primary_key=True, serialize=False)),
                ('operazione', models.CharField(max_length=5)),
                ('num_contratti', models.IntegerField()),
                ('descrizione', models.CharField(max_length=200)),
                ('prezzo', models.FloatField()),
                ('valuta', models.CharField(max_length=3)),
                ('data_ora', models.DateTimeField()),
                ('commissione', models.FloatField()),
                ('profitto_perdita', models.FloatField(blank=True, max_length=100, null=True)),
                ('commento', models.CharField(max_length=200)),
                ('descrizione12', models.CharField(max_length=12)),
            ],
        ),
    ]
