# Generated by Django 3.0.14 on 2022-12-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operazione', models.CharField(max_length=5)),
                ('num_contratti', models.IntegerField()),
                ('descrizione', models.CharField(max_length=200)),
                ('prezzo', models.FloatField()),
                ('valuta', models.CharField(max_length=3)),
                ('data_ora', models.DateTimeField()),
                ('commissione', models.FloatField()),
                ('profitto_perdita', models.FloatField(blank=True, max_length=100, null=True)),
                ('commento', models.CharField(max_length=200)),
                ('descrizione12', models.CharField(max_length=12)),
            ],
        ),
    ]
